import { INITIAL_DATA } from "./seed-data";

const DB_KEY = "eventsphere_db_v1";

// Helper to load db
const loadDB = () => {
  const stored = localStorage.getItem(DB_KEY);
  if (!stored) {
    localStorage.setItem(DB_KEY, JSON.stringify(INITIAL_DATA));
    return INITIAL_DATA;
  }
  return JSON.parse(stored);
};

// Helper to save db
const saveDB = (data: any) => {
  localStorage.setItem(DB_KEY, JSON.stringify(data));
  // Dispatch event for reactive updates (simple polling/subscription simulation)
  window.dispatchEvent(new Event("db-update"));
};

// Generic query function
export const query = (collection: string, filterFn?: (item: any) => boolean) => {
  const db = loadDB();
  const list = db[collection] || [];
  if (filterFn) {
    return list.filter(filterFn);
  }
  return list;
};

// Generic insert function
export const insert = (collection: string, item: any) => {
  const db = loadDB();
  const newItem = { ...item, _id: crypto.randomUUID(), _creationTime: Date.now() };
  if (!db[collection]) db[collection] = [];
  db[collection].push(newItem);
  saveDB(db);
  return newItem._id;
};

// Generic update function
export const update = (collection: string, id: string, updates: any) => {
  const db = loadDB();
  if (!db[collection]) return null;

  const index = db[collection].findIndex((item: any) => item._id === id);
  if (index === -1) return null;

  db[collection][index] = { ...db[collection][index], ...updates };
  saveDB(db);
  return db[collection][index];
};

// Generic remove function
export const remove = (collection: string, id: string) => {
  const db = loadDB();
  if (!db[collection]) return;

  db[collection] = db[collection].filter((item: any) => item._id !== id);
  saveDB(db);
};

// Mock specific Convex API calls 
// This object mimics the structure of `api` generated by Convex
export const localApi = {
  events: {
    getFeaturedEvents: "events:featured",
    getTestimonials: "testimonials:all",
    getAllEvents: "events:all",
    getEventById: "events:getById",
    getServices: "services:all",
    getTeam: "team:all",
    create: "events:create",
    remove: "events:delete",
  },
  bookings: {
    getAll: "bookings:all",
    getByUser: "bookings:getByUser",
    create: "bookings:create",
    updateStatus: "bookings:updateStatus",
    remove: "bookings:delete",
  }
};

const API_BASE_URL = "http://localhost:5000/api";

// Actually implementing the logic for the "queries" above
export const resolvers = {
  "events:featured": async () => {
    try {
      const response = await fetch(`${API_BASE_URL}/events`);
      if (response.ok) {
        const events = await response.json();
        return events.filter((e: any) => e.isFeatured);
      }
    } catch (error) {
      console.error("Failed to fetch featured events from server, falling back to local", error);
    }
    return query("events", (e) => e.isFeatured);
  },
  "testimonials:all": () => query("testimonials"),
  "events:all": async () => {
    try {
      const response = await fetch(`${API_BASE_URL}/events`);
      if (response.ok) {
        return await response.json();
      }
    } catch (error) {
      console.error("Failed to fetch events from server, falling back to local", error);
    }
    return query("events");
  },
  "events:getById": async (args: { id: string }) => {
    try {
      const response = await fetch(`${API_BASE_URL}/events`);
      if (response.ok) {
        const events = await response.json();
        const event = events.find((e: any) => e._id === args.id);
        if (event) return event;
      }
    } catch (error) {
      console.error("Failed to fetch event by id from server, falling back to local", error);
    }
    const events = query("events");
    // @ts-ignore
    return events.find((e: any) => e._id === args.id);
  },
  "services:all": () => query("services"),
  "team:all": () => query("team"),
  "bookings:create": async (args: any) => {
    const response = await fetch(`${API_BASE_URL}/bookings`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(args),
    });
    const result = await response.json();
    window.dispatchEvent(new CustomEvent("db-update"));
    return result;
  },
  "events:create": async (args: any) => {
    try {
      const response = await fetch(`${API_BASE_URL}/events`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(args),
      });
      if (response.ok) {
        const newEvent = await response.json();
        window.dispatchEvent(new Event("db-update"));
        return newEvent;
      }
    } catch (error) {
      console.error("Failed to create event on server", error);
    }
    return insert("events", args);
  },
  "events:delete": async (args: { id: string }) => {
    const response = await fetch(`${API_BASE_URL}/events/${args.id}`, {
      method: "DELETE",
    });
    const result = await response.json();
    window.dispatchEvent(new CustomEvent("db-update"));
    return result;
  },

  // Bookings
  "bookings:all": async () => {
    const response = await fetch(`${API_BASE_URL}/bookings`);
    return await response.json();
  },

  "bookings:getByUser": async (args: { email: string }) => {
    const response = await fetch(`${API_BASE_URL}/bookings/user/${args.email}`);
    return await response.json();
  },

  "bookings:updateStatus": async (args: { id: string; status: string }) => {
    const response = await fetch(`${API_BASE_URL}/bookings/${args.id}/status`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: args.status }),
    });
    const result = await response.json();
    window.dispatchEvent(new CustomEvent("db-update"));
    return result;
  },

  "bookings:delete": async (args: { id: string }) => {
    const response = await fetch(`${API_BASE_URL}/bookings/${args.id}`, {
      method: "DELETE",
    });
    const result = await response.json();
    window.dispatchEvent(new CustomEvent("db-update"));
    return result;
  },
};
