import { INITIAL_DATA } from "./seed-data";

const DB_KEY = "eventsphere_db_v1";

// Helper to load db
const loadDB = () => {
  const stored = localStorage.getItem(DB_KEY);
  if (!stored) {
    localStorage.setItem(DB_KEY, JSON.stringify(INITIAL_DATA));
    return INITIAL_DATA;
  }
  return JSON.parse(stored);
};

// Helper to save db
const saveDB = (data: any) => {
  localStorage.setItem(DB_KEY, JSON.stringify(data));
  // Dispatch event for reactive updates (simple polling/subscription simulation)
  window.dispatchEvent(new Event("db-update"));
};

// Generic query function
export const query = (collection: string, filterFn?: (item: any) => boolean) => {
  const db = loadDB();
  const list = db[collection] || [];
  if (filterFn) {
    return list.filter(filterFn);
  }
  return list;
};

// Generic insert function
export const insert = (collection: string, item: any) => {
  const db = loadDB();
  const newItem = { ...item, _id: crypto.randomUUID(), _creationTime: Date.now() };
  if (!db[collection]) db[collection] = [];
  db[collection].push(newItem);
  saveDB(db);
  return newItem._id;
};

// Generic update function
export const update = (collection: string, id: string, updates: any) => {
  const db = loadDB();
  if (!db[collection]) return null;
  
  const index = db[collection].findIndex((item: any) => item._id === id);
  if (index === -1) return null;

  db[collection][index] = { ...db[collection][index], ...updates };
  saveDB(db);
  return db[collection][index];
};

// Generic remove function
export const remove = (collection: string, id: string) => {
  const db = loadDB();
  if (!db[collection]) return;
  
  db[collection] = db[collection].filter((item: any) => item._id !== id);
  saveDB(db);
};

// Mock specific Convex API calls 
// This object mimics the structure of `api` generated by Convex
export const localApi = {
  events: {
    getFeaturedEvents: "events:featured",
    getTestimonials: "testimonials:all",
    getAllEvents: "events:all",
    getEventById: "events:getById",
    getServices: "services:all",
    getTeam: "team:all",
  },
  bookings: {
    create: "bookings:create",
  }
};

// Actually implementing the logic for the "queries" above
export const resolvers = {
  "events:featured": () => query("events", (e) => e.isFeatured),
  "testimonials:all": () => query("testimonials"),
  "events:all": () => query("events"),
  "events:getById": (args: { id: string }) => {
    const events = query("events");
    // @ts-ignore
    return events.find((e: any) => e._id === args.id);
  },
  "services:all": () => query("services"),
  "team:all": () => query("team"),
  "bookings:create": (args: any) => insert("bookings", args),
};
